/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCalendarWidget>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *sezioneGestione;
    QTabWidget *tabWidget_2;
    QWidget *startGestore;
    QPushButton *bottoneInserimento;
    QLabel *LOGOUNICAL_2;
    QLabel *freccia_2;
    QLabel *label_45;
    QLabel *label_46;
    QWidget *AutoriGestore;
    QLabel *label_22;
    QListWidget *listaAggiornaAutori;
    QPushButton *aggiornaAutori;
    QPushButton *homeInserimento_3;
    QWidget *ConferenzeGestione;
    QLabel *label_23;
    QListWidget *listaAggiornataConferenze;
    QPushButton *aggiornaConferenze;
    QPushButton *homeInserimento_4;
    QWidget *RivisteGestione;
    QLabel *label_24;
    QPushButton *aggiornaRiviste;
    QListWidget *listaAggiornamentoRiviste;
    QPushButton *homeInserimento_5;
    QWidget *ArticoliGestione;
    QPushButton *aggiornaArticoli;
    QListWidget *listaAggiornamentoArticoli;
    QLabel *label_35;
    QPushButton *pushButton;
    QWidget *sezioneArticoli_1;
    QListWidget *listaArticoliConferenze;
    QLineEdit *ricercaConferenzaLuogo;
    QPushButton *bottoneConferenza;
    QLabel *label_42;
    QPushButton *homeGestore;
    QLineEdit *ricercaRivista;
    QPushButton *bottoneRivista_Ricerca;
    QListWidget *listaArticoliRiviste;
    QLabel *label_47;
    QLabel *label_48;
    QPushButton *bottoneKeyword_Ricerca;
    QLineEdit *ricercaKeyword;
    QListWidget *listaArticoliKeyword;
    QPushButton *homeInserimento;
    QPushButton *goToPage2;
    QLineEdit *ricercaConferenza;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_53;
    QLabel *label_54;
    QLineEdit *ricercaRivistaVolume;
    QWidget *sezioneArticoli_3;
    QPushButton *homeGestore_7;
    QPushButton *backToPag2;
    QPushButton *homeInserimento_6;
    QLineEdit *articoliKeywordAnnoDecrescente;
    QLabel *label_140;
    QPushButton *bottone_ArticoliKeywordAnnoDecrescente;
    QListWidget *listaArticoliKeywordAnnoDecrescente;
    QLabel *label_141;
    QWidget *sezioneArticoli_2;
    QListWidget *listaMediaAutori;
    QLineEdit *mediaAutore;
    QPushButton *bottone_mediaAutori;
    QLabel *label_38;
    QPushButton *homeInserimento_2;
    QPushButton *homeGestore_2;
    QPushButton *backToPag1;
    QLabel *label_136;
    QPushButton *bottone_keywordRedditizie;
    QListWidget *listakeywordRedditizie;
    QListWidget *listaAutori_2;
    QLabel *label_137;
    QLabel *label_138;
    QListWidget *listaArticoliAutorePrezzo;
    QLineEdit *articoliAutorePrezzo;
    QPushButton *bottone_ArticoliAutorePrezzo;
    QLabel *label_139;
    QListWidget *listaArticoliAutorePrezzoAlto;
    QLabel *label_144;
    QLabel *label_145;
    QPushButton *bottone_ArticoliAutorePrezzoAlto;
    QLineEdit *articoliAutorePrezzoAlto;
    QPushButton *goToPage3;
    QWidget *sezioneInserimento;
    QTabWidget *tabWidget;
    QWidget *START;
    QPushButton *bottoneGestione;
    QLabel *LOGOUNICAL;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *freccia;
    QWidget *SezioneAutori;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *nomeAutore;
    QLineEdit *cognomeAutore;
    QLabel *label_5;
    QLineEdit *idAutore;
    QPushButton *bottoneAutore;
    QListWidget *listaAut;
    QLabel *label;
    QLineEdit *afferenza;
    QLabel *label_6;
    QPushButton *bottoneAfferenza;
    QPushButton *annullaAutore;
    QPushButton *homeGestore_3;
    QWidget *SezioneConferenza;
    QLabel *label_7;
    QLineEdit *nomeConferenza;
    QLabel *label_8;
    QLineEdit *luogoConferenza;
    QLineEdit *acronimoConferenza;
    QLabel *label_10;
    QLabel *label_11;
    QSpinBox *numeroPartecipanti;
    QCalendarWidget *dataConferenza;
    QLabel *label_9;
    QLabel *label_12;
    QPushButton *bottoneConferenze;
    QListWidget *listaOrg;
    QLabel *label_13;
    QLabel *label_14;
    QPushButton *bottoneOrganizzatori;
    QLineEdit *organizzatore;
    QPushButton *annullaConferenza;
    QPushButton *homeGestore_4;
    QWidget *SezioneRivista;
    QLabel *label_15;
    QLineEdit *nomeRivista;
    QCalendarWidget *dataRivista;
    QLabel *label_16;
    QLabel *label_17;
    QLineEdit *acronimoRivista;
    QLabel *label_18;
    QLabel *label_19;
    QLineEdit *volumeRivista;
    QLineEdit *editoreRivista;
    QLabel *label_20;
    QPushButton *bottoneRivista;
    QLabel *label_21;
    QListWidget *listaRivista;
    QPushButton *annullaRivista;
    QPushButton *homeGestore_5;
    QWidget *SezioneArticoli;
    QLabel *label_26;
    QLabel *label_27;
    QLineEdit *identificativoArticolo;
    QLabel *label_28;
    QSpinBox *numeroPagineArticolo;
    QLineEdit *titoloArticolo;
    QLabel *label_29;
    QLabel *label_25;
    QLabel *label_32;
    QLineEdit *aggiuntaAutoreArticolo;
    QLineEdit *aggiuntaKeyword;
    QPushButton *bottoneOkAutori;
    QPushButton *bottoneOkKeyword;
    QPushButton *bottoneArticolo;
    QLabel *label_33;
    QListWidget *listaArticoli;
    QLabel *label_30;
    QLabel *label_31;
    QDoubleSpinBox *prezzoArticolo;
    QLabel *label_34;
    QLineEdit *aggiuntaArticoloCorrelato;
    QPushButton *bottoneArticoloCorrelato;
    QLabel *label_36;
    QLineEdit *rivistaRiferimento;
    QLabel *label_37;
    QLineEdit *conferenzaRiferimento;
    QPushButton *annullaArticolo;
    QPushButton *homeGestore_6;
    QLabel *label_49;
    QLabel *label_51;
    QWidget *tab;
    QLabel *label_39;
    QPushButton *importa_autori;
    QPushButton *importa_conferenze;
    QPushButton *importa_riviste;
    QPushButton *importa_articoli;
    QMenuBar *menubar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1058, 662);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(19, 0, 1021, 571));
        sezioneGestione = new QWidget();
        sezioneGestione->setObjectName(QString::fromUtf8("sezioneGestione"));
        tabWidget_2 = new QTabWidget(sezioneGestione);
        tabWidget_2->setObjectName(QString::fromUtf8("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(10, 20, 991, 551));
        QFont font;
        font.setPointSize(10);
        tabWidget_2->setFont(font);
        startGestore = new QWidget();
        startGestore->setObjectName(QString::fromUtf8("startGestore"));
        bottoneInserimento = new QPushButton(startGestore);
        bottoneInserimento->setObjectName(QString::fromUtf8("bottoneInserimento"));
        bottoneInserimento->setGeometry(QRect(690, 400, 241, 61));
        bottoneInserimento->setFont(font);
        bottoneInserimento->setCursor(QCursor(Qt::PointingHandCursor));
        LOGOUNICAL_2 = new QLabel(startGestore);
        LOGOUNICAL_2->setObjectName(QString::fromUtf8("LOGOUNICAL_2"));
        LOGOUNICAL_2->setGeometry(QRect(10, 30, 441, 211));
        LOGOUNICAL_2->setPixmap(QPixmap(QString::fromUtf8(":/img/img/logounical.png")));
        freccia_2 = new QLabel(startGestore);
        freccia_2->setObjectName(QString::fromUtf8("freccia_2"));
        freccia_2->setGeometry(QRect(790, 310, 71, 61));
        freccia_2->setPixmap(QPixmap(QString::fromUtf8(":/img/img/freccia.png")));
        label_45 = new QLabel(startGestore);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(30, 240, 961, 61));
        QFont font1;
        font1.setFamily(QString::fromUtf8("HP Simplified"));
        font1.setPointSize(13);
        font1.setBold(false);
        font1.setWeight(50);
        label_45->setFont(font1);
        label_46 = new QLabel(startGestore);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(460, 80, 511, 81));
        QFont font2;
        font2.setFamily(QString::fromUtf8("HP Simplified Jpan"));
        font2.setPointSize(21);
        font2.setBold(true);
        font2.setWeight(75);
        label_46->setFont(font2);
        tabWidget_2->addTab(startGestore, QString());
        AutoriGestore = new QWidget();
        AutoriGestore->setObjectName(QString::fromUtf8("AutoriGestore"));
        label_22 = new QLabel(AutoriGestore);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(350, 40, 281, 51));
        QFont font3;
        font3.setPointSize(10);
        font3.setBold(true);
        font3.setWeight(75);
        label_22->setFont(font3);
        listaAggiornaAutori = new QListWidget(AutoriGestore);
        listaAggiornaAutori->setObjectName(QString::fromUtf8("listaAggiornaAutori"));
        listaAggiornaAutori->setGeometry(QRect(35, 90, 911, 341));
        aggiornaAutori = new QPushButton(AutoriGestore);
        aggiornaAutori->setObjectName(QString::fromUtf8("aggiornaAutori"));
        aggiornaAutori->setGeometry(QRect(450, 450, 131, 28));
        aggiornaAutori->setFont(font3);
        homeInserimento_3 = new QPushButton(AutoriGestore);
        homeInserimento_3->setObjectName(QString::fromUtf8("homeInserimento_3"));
        homeInserimento_3->setGeometry(QRect(790, 20, 181, 28));
        QFont font4;
        font4.setFamily(QString::fromUtf8("MS Serif"));
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        homeInserimento_3->setFont(font4);
        tabWidget_2->addTab(AutoriGestore, QString());
        ConferenzeGestione = new QWidget();
        ConferenzeGestione->setObjectName(QString::fromUtf8("ConferenzeGestione"));
        label_23 = new QLabel(ConferenzeGestione);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(350, 40, 331, 51));
        label_23->setFont(font3);
        listaAggiornataConferenze = new QListWidget(ConferenzeGestione);
        listaAggiornataConferenze->setObjectName(QString::fromUtf8("listaAggiornataConferenze"));
        listaAggiornataConferenze->setGeometry(QRect(35, 90, 911, 341));
        aggiornaConferenze = new QPushButton(ConferenzeGestione);
        aggiornaConferenze->setObjectName(QString::fromUtf8("aggiornaConferenze"));
        aggiornaConferenze->setGeometry(QRect(440, 450, 131, 28));
        aggiornaConferenze->setFont(font3);
        homeInserimento_4 = new QPushButton(ConferenzeGestione);
        homeInserimento_4->setObjectName(QString::fromUtf8("homeInserimento_4"));
        homeInserimento_4->setGeometry(QRect(790, 20, 181, 28));
        homeInserimento_4->setFont(font4);
        tabWidget_2->addTab(ConferenzeGestione, QString());
        RivisteGestione = new QWidget();
        RivisteGestione->setObjectName(QString::fromUtf8("RivisteGestione"));
        label_24 = new QLabel(RivisteGestione);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(350, 30, 331, 51));
        label_24->setFont(font3);
        aggiornaRiviste = new QPushButton(RivisteGestione);
        aggiornaRiviste->setObjectName(QString::fromUtf8("aggiornaRiviste"));
        aggiornaRiviste->setGeometry(QRect(430, 450, 131, 28));
        aggiornaRiviste->setFont(font3);
        listaAggiornamentoRiviste = new QListWidget(RivisteGestione);
        listaAggiornamentoRiviste->setObjectName(QString::fromUtf8("listaAggiornamentoRiviste"));
        listaAggiornamentoRiviste->setGeometry(QRect(35, 90, 911, 341));
        homeInserimento_5 = new QPushButton(RivisteGestione);
        homeInserimento_5->setObjectName(QString::fromUtf8("homeInserimento_5"));
        homeInserimento_5->setGeometry(QRect(790, 20, 181, 28));
        homeInserimento_5->setFont(font4);
        tabWidget_2->addTab(RivisteGestione, QString());
        ArticoliGestione = new QWidget();
        ArticoliGestione->setObjectName(QString::fromUtf8("ArticoliGestione"));
        aggiornaArticoli = new QPushButton(ArticoliGestione);
        aggiornaArticoli->setObjectName(QString::fromUtf8("aggiornaArticoli"));
        aggiornaArticoli->setGeometry(QRect(440, 470, 131, 28));
        aggiornaArticoli->setFont(font3);
        listaAggiornamentoArticoli = new QListWidget(ArticoliGestione);
        listaAggiornamentoArticoli->setObjectName(QString::fromUtf8("listaAggiornamentoArticoli"));
        listaAggiornamentoArticoli->setGeometry(QRect(40, 110, 901, 341));
        label_35 = new QLabel(ArticoliGestione);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(330, 30, 331, 51));
        label_35->setFont(font3);
        pushButton = new QPushButton(ArticoliGestione);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(740, 30, 201, 51));
        tabWidget_2->addTab(ArticoliGestione, QString());
        stackedWidget->addWidget(sezioneGestione);
        sezioneArticoli_1 = new QWidget();
        sezioneArticoli_1->setObjectName(QString::fromUtf8("sezioneArticoli_1"));
        listaArticoliConferenze = new QListWidget(sezioneArticoli_1);
        listaArticoliConferenze->setObjectName(QString::fromUtf8("listaArticoliConferenze"));
        listaArticoliConferenze->setGeometry(QRect(20, 150, 451, 151));
        ricercaConferenzaLuogo = new QLineEdit(sezioneArticoli_1);
        ricercaConferenzaLuogo->setObjectName(QString::fromUtf8("ricercaConferenzaLuogo"));
        ricercaConferenzaLuogo->setGeometry(QRect(260, 70, 71, 41));
        bottoneConferenza = new QPushButton(sezioneArticoli_1);
        bottoneConferenza->setObjectName(QString::fromUtf8("bottoneConferenza"));
        bottoneConferenza->setGeometry(QRect(360, 70, 51, 41));
        label_42 = new QLabel(sezioneArticoli_1);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(20, 20, 471, 41));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Yu Gothic UI Semibold"));
        font5.setPointSize(10);
        font5.setBold(true);
        font5.setWeight(75);
        label_42->setFont(font5);
        homeGestore = new QPushButton(sezioneArticoli_1);
        homeGestore->setObjectName(QString::fromUtf8("homeGestore"));
        homeGestore->setGeometry(QRect(40, 520, 181, 28));
        QFont font6;
        font6.setFamily(QString::fromUtf8("MS Serif"));
        font6.setBold(true);
        font6.setWeight(75);
        homeGestore->setFont(font6);
        ricercaRivista = new QLineEdit(sezioneArticoli_1);
        ricercaRivista->setObjectName(QString::fromUtf8("ricercaRivista"));
        ricercaRivista->setGeometry(QRect(650, 70, 71, 41));
        bottoneRivista_Ricerca = new QPushButton(sezioneArticoli_1);
        bottoneRivista_Ricerca->setObjectName(QString::fromUtf8("bottoneRivista_Ricerca"));
        bottoneRivista_Ricerca->setGeometry(QRect(860, 70, 51, 41));
        listaArticoliRiviste = new QListWidget(sezioneArticoli_1);
        listaArticoliRiviste->setObjectName(QString::fromUtf8("listaArticoliRiviste"));
        listaArticoliRiviste->setGeometry(QRect(520, 150, 451, 151));
        label_47 = new QLabel(sezioneArticoli_1);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(580, 20, 351, 41));
        label_47->setFont(font5);
        label_48 = new QLabel(sezioneArticoli_1);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(370, 320, 321, 41));
        label_48->setFont(font5);
        bottoneKeyword_Ricerca = new QPushButton(sezioneArticoli_1);
        bottoneKeyword_Ricerca->setObjectName(QString::fromUtf8("bottoneKeyword_Ricerca"));
        bottoneKeyword_Ricerca->setGeometry(QRect(610, 360, 51, 41));
        ricercaKeyword = new QLineEdit(sezioneArticoli_1);
        ricercaKeyword->setObjectName(QString::fromUtf8("ricercaKeyword"));
        ricercaKeyword->setGeometry(QRect(350, 360, 231, 41));
        listaArticoliKeyword = new QListWidget(sezioneArticoli_1);
        listaArticoliKeyword->setObjectName(QString::fromUtf8("listaArticoliKeyword"));
        listaArticoliKeyword->setGeometry(QRect(270, 410, 451, 151));
        homeInserimento = new QPushButton(sezioneArticoli_1);
        homeInserimento->setObjectName(QString::fromUtf8("homeInserimento"));
        homeInserimento->setGeometry(QRect(40, 470, 181, 28));
        homeInserimento->setFont(font6);
        goToPage2 = new QPushButton(sezioneArticoli_1);
        goToPage2->setObjectName(QString::fromUtf8("goToPage2"));
        goToPage2->setGeometry(QRect(800, 500, 181, 28));
        goToPage2->setFont(font6);
        ricercaConferenza = new QLineEdit(sezioneArticoli_1);
        ricercaConferenza->setObjectName(QString::fromUtf8("ricercaConferenza"));
        ricercaConferenza->setGeometry(QRect(110, 70, 71, 41));
        label_40 = new QLabel(sezioneArticoli_1);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(30, 70, 81, 41));
        label_41 = new QLabel(sezioneArticoli_1);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(210, 70, 51, 41));
        label_53 = new QLabel(sezioneArticoli_1);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(560, 70, 81, 41));
        label_54 = new QLabel(sezioneArticoli_1);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(740, 70, 51, 41));
        ricercaRivistaVolume = new QLineEdit(sezioneArticoli_1);
        ricercaRivistaVolume->setObjectName(QString::fromUtf8("ricercaRivistaVolume"));
        ricercaRivistaVolume->setGeometry(QRect(780, 70, 71, 41));
        stackedWidget->addWidget(sezioneArticoli_1);
        sezioneArticoli_3 = new QWidget();
        sezioneArticoli_3->setObjectName(QString::fromUtf8("sezioneArticoli_3"));
        homeGestore_7 = new QPushButton(sezioneArticoli_3);
        homeGestore_7->setObjectName(QString::fromUtf8("homeGestore_7"));
        homeGestore_7->setGeometry(QRect(30, 500, 181, 28));
        homeGestore_7->setFont(font6);
        backToPag2 = new QPushButton(sezioneArticoli_3);
        backToPag2->setObjectName(QString::fromUtf8("backToPag2"));
        backToPag2->setGeometry(QRect(30, 40, 181, 28));
        backToPag2->setFont(font6);
        homeInserimento_6 = new QPushButton(sezioneArticoli_3);
        homeInserimento_6->setObjectName(QString::fromUtf8("homeInserimento_6"));
        homeInserimento_6->setGeometry(QRect(30, 450, 181, 28));
        homeInserimento_6->setFont(font6);
        articoliKeywordAnnoDecrescente = new QLineEdit(sezioneArticoli_3);
        articoliKeywordAnnoDecrescente->setObjectName(QString::fromUtf8("articoliKeywordAnnoDecrescente"));
        articoliKeywordAnnoDecrescente->setGeometry(QRect(500, 90, 151, 41));
        label_140 = new QLabel(sezioneArticoli_3);
        label_140->setObjectName(QString::fromUtf8("label_140"));
        label_140->setGeometry(QRect(460, 80, 41, 51));
        QFont font7;
        font7.setPointSize(14);
        label_140->setFont(font7);
        bottone_ArticoliKeywordAnnoDecrescente = new QPushButton(sezioneArticoli_3);
        bottone_ArticoliKeywordAnnoDecrescente->setObjectName(QString::fromUtf8("bottone_ArticoliKeywordAnnoDecrescente"));
        bottone_ArticoliKeywordAnnoDecrescente->setGeometry(QRect(670, 90, 51, 41));
        listaArticoliKeywordAnnoDecrescente = new QListWidget(sezioneArticoli_3);
        listaArticoliKeywordAnnoDecrescente->setObjectName(QString::fromUtf8("listaArticoliKeywordAnnoDecrescente"));
        listaArticoliKeywordAnnoDecrescente->setGeometry(QRect(310, 140, 591, 281));
        QFont font8;
        font8.setPointSize(9);
        listaArticoliKeywordAnnoDecrescente->setFont(font8);
        label_141 = new QLabel(sezioneArticoli_3);
        label_141->setObjectName(QString::fromUtf8("label_141"));
        label_141->setGeometry(QRect(470, 40, 241, 41));
        QFont font9;
        font9.setFamily(QString::fromUtf8("HP Simplified"));
        font9.setPointSize(10);
        label_141->setFont(font9);
        stackedWidget->addWidget(sezioneArticoli_3);
        sezioneArticoli_2 = new QWidget();
        sezioneArticoli_2->setObjectName(QString::fromUtf8("sezioneArticoli_2"));
        listaMediaAutori = new QListWidget(sezioneArticoli_2);
        listaMediaAutori->setObjectName(QString::fromUtf8("listaMediaAutori"));
        listaMediaAutori->setGeometry(QRect(640, 150, 171, 71));
        QFont font10;
        font10.setPointSize(20);
        listaMediaAutori->setFont(font10);
        mediaAutore = new QLineEdit(sezioneArticoli_2);
        mediaAutore->setObjectName(QString::fromUtf8("mediaAutore"));
        mediaAutore->setGeometry(QRect(640, 90, 111, 41));
        bottone_mediaAutori = new QPushButton(sezioneArticoli_2);
        bottone_mediaAutori->setObjectName(QString::fromUtf8("bottone_mediaAutori"));
        bottone_mediaAutori->setGeometry(QRect(760, 90, 51, 41));
        label_38 = new QLabel(sezioneArticoli_2);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(640, 40, 171, 31));
        label_38->setFont(font9);
        homeInserimento_2 = new QPushButton(sezioneArticoli_2);
        homeInserimento_2->setObjectName(QString::fromUtf8("homeInserimento_2"));
        homeInserimento_2->setGeometry(QRect(50, 430, 181, 28));
        homeInserimento_2->setFont(font6);
        homeGestore_2 = new QPushButton(sezioneArticoli_2);
        homeGestore_2->setObjectName(QString::fromUtf8("homeGestore_2"));
        homeGestore_2->setGeometry(QRect(50, 480, 181, 28));
        homeGestore_2->setFont(font6);
        backToPag1 = new QPushButton(sezioneArticoli_2);
        backToPag1->setObjectName(QString::fromUtf8("backToPag1"));
        backToPag1->setGeometry(QRect(50, 20, 181, 28));
        backToPag1->setFont(font6);
        label_136 = new QLabel(sezioneArticoli_2);
        label_136->setObjectName(QString::fromUtf8("label_136"));
        label_136->setGeometry(QRect(360, 40, 161, 51));
        label_136->setFont(font9);
        bottone_keywordRedditizie = new QPushButton(sezioneArticoli_2);
        bottone_keywordRedditizie->setObjectName(QString::fromUtf8("bottone_keywordRedditizie"));
        bottone_keywordRedditizie->setGeometry(QRect(370, 200, 131, 31));
        listakeywordRedditizie = new QListWidget(sezioneArticoli_2);
        listakeywordRedditizie->setObjectName(QString::fromUtf8("listakeywordRedditizie"));
        listakeywordRedditizie->setGeometry(QRect(280, 90, 301, 101));
        QFont font11;
        font11.setPointSize(19);
        listakeywordRedditizie->setFont(font11);
        listaAutori_2 = new QListWidget(sezioneArticoli_2);
        listaAutori_2->setObjectName(QString::fromUtf8("listaAutori_2"));
        listaAutori_2->setGeometry(QRect(50, 130, 181, 261));
        label_137 = new QLabel(sezioneArticoli_2);
        label_137->setObjectName(QString::fromUtf8("label_137"));
        label_137->setGeometry(QRect(70, 60, 151, 71));
        QFont font12;
        font12.setFamily(QString::fromUtf8("HP Simplified"));
        font12.setPointSize(10);
        font12.setBold(false);
        font12.setWeight(50);
        label_137->setFont(font12);
        label_138 = new QLabel(sezioneArticoli_2);
        label_138->setObjectName(QString::fromUtf8("label_138"));
        label_138->setGeometry(QRect(320, 250, 241, 41));
        label_138->setFont(font9);
        listaArticoliAutorePrezzo = new QListWidget(sezioneArticoli_2);
        listaArticoliAutorePrezzo->setObjectName(QString::fromUtf8("listaArticoliAutorePrezzo"));
        listaArticoliAutorePrezzo->setGeometry(QRect(300, 350, 271, 161));
        listaArticoliAutorePrezzo->setFont(font8);
        articoliAutorePrezzo = new QLineEdit(sezioneArticoli_2);
        articoliAutorePrezzo->setObjectName(QString::fromUtf8("articoliAutorePrezzo"));
        articoliAutorePrezzo->setGeometry(QRect(350, 300, 151, 41));
        bottone_ArticoliAutorePrezzo = new QPushButton(sezioneArticoli_2);
        bottone_ArticoliAutorePrezzo->setObjectName(QString::fromUtf8("bottone_ArticoliAutorePrezzo"));
        bottone_ArticoliAutorePrezzo->setGeometry(QRect(520, 300, 51, 41));
        label_139 = new QLabel(sezioneArticoli_2);
        label_139->setObjectName(QString::fromUtf8("label_139"));
        label_139->setGeometry(QRect(310, 290, 41, 51));
        label_139->setFont(font7);
        listaArticoliAutorePrezzoAlto = new QListWidget(sezioneArticoli_2);
        listaArticoliAutorePrezzoAlto->setObjectName(QString::fromUtf8("listaArticoliAutorePrezzoAlto"));
        listaArticoliAutorePrezzoAlto->setGeometry(QRect(640, 360, 271, 161));
        listaArticoliAutorePrezzoAlto->setFont(font8);
        label_144 = new QLabel(sezioneArticoli_2);
        label_144->setObjectName(QString::fromUtf8("label_144"));
        label_144->setGeometry(QRect(660, 260, 241, 41));
        label_144->setFont(font9);
        label_145 = new QLabel(sezioneArticoli_2);
        label_145->setObjectName(QString::fromUtf8("label_145"));
        label_145->setGeometry(QRect(650, 300, 41, 51));
        label_145->setFont(font7);
        bottone_ArticoliAutorePrezzoAlto = new QPushButton(sezioneArticoli_2);
        bottone_ArticoliAutorePrezzoAlto->setObjectName(QString::fromUtf8("bottone_ArticoliAutorePrezzoAlto"));
        bottone_ArticoliAutorePrezzoAlto->setGeometry(QRect(860, 310, 51, 41));
        articoliAutorePrezzoAlto = new QLineEdit(sezioneArticoli_2);
        articoliAutorePrezzoAlto->setObjectName(QString::fromUtf8("articoliAutorePrezzoAlto"));
        articoliAutorePrezzoAlto->setGeometry(QRect(690, 310, 151, 41));
        goToPage3 = new QPushButton(sezioneArticoli_2);
        goToPage3->setObjectName(QString::fromUtf8("goToPage3"));
        goToPage3->setGeometry(QRect(820, 540, 181, 28));
        goToPage3->setFont(font6);
        stackedWidget->addWidget(sezioneArticoli_2);
        sezioneInserimento = new QWidget();
        sezioneInserimento->setObjectName(QString::fromUtf8("sezioneInserimento"));
        tabWidget = new QTabWidget(sezioneInserimento);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 20, 991, 591));
        QFont font13;
        font13.setPointSize(10);
        font13.setBold(false);
        font13.setWeight(50);
        tabWidget->setFont(font13);
        START = new QWidget();
        START->setObjectName(QString::fromUtf8("START"));
        bottoneGestione = new QPushButton(START);
        bottoneGestione->setObjectName(QString::fromUtf8("bottoneGestione"));
        bottoneGestione->setGeometry(QRect(720, 400, 201, 61));
        bottoneGestione->setCursor(QCursor(Qt::PointingHandCursor));
        LOGOUNICAL = new QLabel(START);
        LOGOUNICAL->setObjectName(QString::fromUtf8("LOGOUNICAL"));
        LOGOUNICAL->setGeometry(QRect(10, 30, 451, 211));
        LOGOUNICAL->setPixmap(QPixmap(QString::fromUtf8(":/img/img/logounical.png")));
        label_43 = new QLabel(START);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(470, 80, 491, 81));
        QFont font14;
        font14.setFamily(QString::fromUtf8("HP Simplified Jpan"));
        font14.setPointSize(20);
        font14.setBold(true);
        font14.setWeight(75);
        label_43->setFont(font14);
        label_44 = new QLabel(START);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(20, 240, 961, 71));
        QFont font15;
        font15.setFamily(QString::fromUtf8("HP Simplified"));
        font15.setPointSize(14);
        font15.setBold(false);
        font15.setWeight(50);
        label_44->setFont(font15);
        freccia = new QLabel(START);
        freccia->setObjectName(QString::fromUtf8("freccia"));
        freccia->setGeometry(QRect(790, 310, 81, 61));
        freccia->setPixmap(QPixmap(QString::fromUtf8(":/img/img/freccia.png")));
        tabWidget->addTab(START, QString());
        SezioneAutori = new QWidget();
        SezioneAutori->setObjectName(QString::fromUtf8("SezioneAutori"));
        label_2 = new QLabel(SezioneAutori);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(50, 40, 391, 51));
        QFont font16;
        font16.setFamily(QString::fromUtf8("Stencil"));
        font16.setPointSize(24);
        font16.setBold(false);
        font16.setWeight(50);
        label_2->setFont(font16);
        label_3 = new QLabel(SezioneAutori);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(51, 141, 44, 18));
        QFont font17;
        font17.setPointSize(9);
        font17.setBold(false);
        font17.setWeight(50);
        label_3->setFont(font17);
        label_4 = new QLabel(SezioneAutori);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(359, 141, 67, 18));
        label_4->setFont(font17);
        nomeAutore = new QLineEdit(SezioneAutori);
        nomeAutore->setObjectName(QString::fromUtf8("nomeAutore"));
        nomeAutore->setGeometry(QRect(130, 140, 191, 22));
        cognomeAutore = new QLineEdit(SezioneAutori);
        cognomeAutore->setObjectName(QString::fromUtf8("cognomeAutore"));
        cognomeAutore->setGeometry(QRect(460, 140, 191, 22));
        label_5 = new QLabel(SezioneAutori);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(690, 140, 31, 21));
        label_5->setFont(font17);
        idAutore = new QLineEdit(SezioneAutori);
        idAutore->setObjectName(QString::fromUtf8("idAutore"));
        idAutore->setGeometry(QRect(720, 140, 113, 22));
        bottoneAutore = new QPushButton(SezioneAutori);
        bottoneAutore->setObjectName(QString::fromUtf8("bottoneAutore"));
        bottoneAutore->setGeometry(QRect(380, 190, 141, 31));
        QFont font18;
        font18.setPointSize(9);
        font18.setBold(true);
        font18.setWeight(75);
        bottoneAutore->setFont(font18);
        listaAut = new QListWidget(SezioneAutori);
        listaAut->setObjectName(QString::fromUtf8("listaAut"));
        listaAut->setGeometry(QRect(220, 320, 251, 41));
        label = new QLabel(SezioneAutori);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(50, 320, 171, 41));
        label->setFont(font13);
        afferenza = new QLineEdit(SezioneAutori);
        afferenza->setObjectName(QString::fromUtf8("afferenza"));
        afferenza->setGeometry(QRect(630, 320, 221, 41));
        QFont font19;
        font19.setPointSize(12);
        font19.setBold(false);
        font19.setWeight(50);
        afferenza->setFont(font19);
        label_6 = new QLabel(SezioneAutori);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(540, 320, 91, 41));
        label_6->setFont(font13);
        bottoneAfferenza = new QPushButton(SezioneAutori);
        bottoneAfferenza->setObjectName(QString::fromUtf8("bottoneAfferenza"));
        bottoneAfferenza->setGeometry(QRect(670, 380, 141, 28));
        bottoneAfferenza->setFont(font17);
        annullaAutore = new QPushButton(SezioneAutori);
        annullaAutore->setObjectName(QString::fromUtf8("annullaAutore"));
        annullaAutore->setGeometry(QRect(340, 250, 211, 31));
        homeGestore_3 = new QPushButton(SezioneAutori);
        homeGestore_3->setObjectName(QString::fromUtf8("homeGestore_3"));
        homeGestore_3->setGeometry(QRect(790, 20, 181, 28));
        homeGestore_3->setFont(font4);
        tabWidget->addTab(SezioneAutori, QString());
        SezioneConferenza = new QWidget();
        SezioneConferenza->setObjectName(QString::fromUtf8("SezioneConferenza"));
        label_7 = new QLabel(SezioneConferenza);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(368, 120, 67, 18));
        label_7->setFont(font17);
        nomeConferenza = new QLineEdit(SezioneConferenza);
        nomeConferenza->setObjectName(QString::fromUtf8("nomeConferenza"));
        nomeConferenza->setGeometry(QRect(139, 119, 191, 22));
        label_8 = new QLabel(SezioneConferenza);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(699, 119, 51, 21));
        label_8->setFont(font17);
        luogoConferenza = new QLineEdit(SezioneConferenza);
        luogoConferenza->setObjectName(QString::fromUtf8("luogoConferenza"));
        luogoConferenza->setGeometry(QRect(780, 120, 113, 22));
        acronimoConferenza = new QLineEdit(SezioneConferenza);
        acronimoConferenza->setObjectName(QString::fromUtf8("acronimoConferenza"));
        acronimoConferenza->setGeometry(QRect(469, 119, 191, 22));
        label_10 = new QLabel(SezioneConferenza);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(60, 120, 44, 18));
        label_10->setFont(font17);
        label_11 = new QLabel(SezioneConferenza);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(60, 160, 171, 31));
        numeroPartecipanti = new QSpinBox(SezioneConferenza);
        numeroPartecipanti->setObjectName(QString::fromUtf8("numeroPartecipanti"));
        numeroPartecipanti->setGeometry(QRect(230, 160, 61, 31));
        numeroPartecipanti->setMaximum(9999);
        dataConferenza = new QCalendarWidget(SezioneConferenza);
        dataConferenza->setObjectName(QString::fromUtf8("dataConferenza"));
        dataConferenza->setGeometry(QRect(20, 240, 391, 181));
        dataConferenza->setFont(font17);
        dataConferenza->setCursor(QCursor(Qt::CrossCursor));
        label_9 = new QLabel(SezioneConferenza);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(50, 40, 391, 51));
        label_9->setFont(font16);
        label_12 = new QLabel(SezioneConferenza);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(140, 210, 131, 21));
        bottoneConferenze = new QPushButton(SezioneConferenza);
        bottoneConferenze->setObjectName(QString::fromUtf8("bottoneConferenze"));
        bottoneConferenze->setGeometry(QRect(130, 440, 171, 31));
        bottoneConferenze->setFont(font18);
        listaOrg = new QListWidget(SezioneConferenza);
        listaOrg->setObjectName(QString::fromUtf8("listaOrg"));
        listaOrg->setGeometry(QRect(450, 290, 501, 51));
        QFont font20;
        font20.setPointSize(10);
        font20.setBold(false);
        font20.setItalic(true);
        font20.setWeight(50);
        listaOrg->setFont(font20);
        label_13 = new QLabel(SezioneConferenza);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(570, 250, 261, 31));
        QFont font21;
        font21.setFamily(QString::fromUtf8("8514oem"));
        font21.setPointSize(12);
        font21.setBold(false);
        font21.setUnderline(false);
        font21.setWeight(50);
        label_13->setFont(font21);
        label_14 = new QLabel(SezioneConferenza);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(480, 360, 91, 41));
        QFont font22;
        font22.setFamily(QString::fromUtf8("8514oem"));
        font22.setPointSize(8);
        font22.setBold(false);
        font22.setWeight(50);
        label_14->setFont(font22);
        bottoneOrganizzatori = new QPushButton(SezioneConferenza);
        bottoneOrganizzatori->setObjectName(QString::fromUtf8("bottoneOrganizzatori"));
        bottoneOrganizzatori->setGeometry(QRect(610, 420, 261, 28));
        bottoneOrganizzatori->setFont(font22);
        organizzatore = new QLineEdit(SezioneConferenza);
        organizzatore->setObjectName(QString::fromUtf8("organizzatore"));
        organizzatore->setGeometry(QRect(580, 360, 321, 41));
        organizzatore->setFont(font19);
        annullaConferenza = new QPushButton(SezioneConferenza);
        annullaConferenza->setObjectName(QString::fromUtf8("annullaConferenza"));
        annullaConferenza->setGeometry(QRect(110, 480, 211, 31));
        homeGestore_4 = new QPushButton(SezioneConferenza);
        homeGestore_4->setObjectName(QString::fromUtf8("homeGestore_4"));
        homeGestore_4->setGeometry(QRect(790, 20, 181, 28));
        homeGestore_4->setFont(font4);
        tabWidget->addTab(SezioneConferenza, QString());
        SezioneRivista = new QWidget();
        SezioneRivista->setObjectName(QString::fromUtf8("SezioneRivista"));
        label_15 = new QLabel(SezioneRivista);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(60, 120, 44, 18));
        label_15->setFont(font17);
        nomeRivista = new QLineEdit(SezioneRivista);
        nomeRivista->setObjectName(QString::fromUtf8("nomeRivista"));
        nomeRivista->setGeometry(QRect(139, 119, 191, 22));
        dataRivista = new QCalendarWidget(SezioneRivista);
        dataRivista->setObjectName(QString::fromUtf8("dataRivista"));
        dataRivista->setGeometry(QRect(40, 210, 401, 211));
        dataRivista->setFont(font17);
        dataRivista->setCursor(QCursor(Qt::CrossCursor));
        label_16 = new QLabel(SezioneRivista);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(160, 160, 131, 51));
        label_17 = new QLabel(SezioneRivista);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(368, 120, 67, 18));
        label_17->setFont(font17);
        acronimoRivista = new QLineEdit(SezioneRivista);
        acronimoRivista->setObjectName(QString::fromUtf8("acronimoRivista"));
        acronimoRivista->setGeometry(QRect(469, 119, 191, 22));
        label_18 = new QLabel(SezioneRivista);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(699, 119, 51, 21));
        label_18->setFont(font17);
        label_19 = new QLabel(SezioneRivista);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(50, 40, 391, 51));
        label_19->setFont(font16);
        volumeRivista = new QLineEdit(SezioneRivista);
        volumeRivista->setObjectName(QString::fromUtf8("volumeRivista"));
        volumeRivista->setGeometry(QRect(780, 120, 113, 22));
        editoreRivista = new QLineEdit(SezioneRivista);
        editoreRivista->setObjectName(QString::fromUtf8("editoreRivista"));
        editoreRivista->setGeometry(QRect(470, 170, 191, 22));
        label_20 = new QLabel(SezioneRivista);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(391, 171, 61, 18));
        label_20->setFont(font17);
        bottoneRivista = new QPushButton(SezioneRivista);
        bottoneRivista->setObjectName(QString::fromUtf8("bottoneRivista"));
        bottoneRivista->setGeometry(QRect(700, 160, 191, 41));
        label_21 = new QLabel(SezioneRivista);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(570, 300, 341, 31));
        label_21->setFont(font21);
        listaRivista = new QListWidget(SezioneRivista);
        listaRivista->setObjectName(QString::fromUtf8("listaRivista"));
        listaRivista->setGeometry(QRect(520, 350, 451, 81));
        listaRivista->setFont(font20);
        annullaRivista = new QPushButton(SezioneRivista);
        annullaRivista->setObjectName(QString::fromUtf8("annullaRivista"));
        annullaRivista->setGeometry(QRect(690, 230, 211, 31));
        homeGestore_5 = new QPushButton(SezioneRivista);
        homeGestore_5->setObjectName(QString::fromUtf8("homeGestore_5"));
        homeGestore_5->setGeometry(QRect(790, 20, 181, 28));
        homeGestore_5->setFont(font4);
        tabWidget->addTab(SezioneRivista, QString());
        SezioneArticoli = new QWidget();
        SezioneArticoli->setObjectName(QString::fromUtf8("SezioneArticoli"));
        label_26 = new QLabel(SezioneArticoli);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(369, 119, 51, 21));
        QFont font23;
        font23.setFamily(QString::fromUtf8("HP Simplified"));
        font23.setPointSize(9);
        font23.setBold(false);
        font23.setWeight(50);
        label_26->setFont(font23);
        label_27 = new QLabel(SezioneArticoli);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(60, 120, 44, 18));
        QFont font24;
        font24.setFamily(QString::fromUtf8("HP Simplified"));
        font24.setPointSize(9);
        font24.setBold(false);
        font24.setItalic(false);
        font24.setWeight(50);
        label_27->setFont(font24);
        identificativoArticolo = new QLineEdit(SezioneArticoli);
        identificativoArticolo->setObjectName(QString::fromUtf8("identificativoArticolo"));
        identificativoArticolo->setGeometry(QRect(412, 120, 151, 22));
        label_28 = new QLabel(SezioneArticoli);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(610, 110, 171, 41));
        label_28->setFont(font12);
        numeroPagineArticolo = new QSpinBox(SezioneArticoli);
        numeroPagineArticolo->setObjectName(QString::fromUtf8("numeroPagineArticolo"));
        numeroPagineArticolo->setGeometry(QRect(760, 110, 81, 41));
        numeroPagineArticolo->setMaximum(9999);
        titoloArticolo = new QLineEdit(SezioneArticoli);
        titoloArticolo->setObjectName(QString::fromUtf8("titoloArticolo"));
        titoloArticolo->setGeometry(QRect(129, 119, 201, 22));
        label_29 = new QLabel(SezioneArticoli);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(50, 40, 391, 51));
        label_29->setFont(font16);
        label_25 = new QLabel(SezioneArticoli);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(30, 400, 231, 31));
        label_25->setFont(font3);
        label_32 = new QLabel(SezioneArticoli);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(30, 470, 241, 31));
        label_32->setFont(font3);
        aggiuntaAutoreArticolo = new QLineEdit(SezioneArticoli);
        aggiuntaAutoreArticolo->setObjectName(QString::fromUtf8("aggiuntaAutoreArticolo"));
        aggiuntaAutoreArticolo->setGeometry(QRect(250, 390, 251, 51));
        aggiuntaKeyword = new QLineEdit(SezioneArticoli);
        aggiuntaKeyword->setObjectName(QString::fromUtf8("aggiuntaKeyword"));
        aggiuntaKeyword->setGeometry(QRect(240, 460, 261, 51));
        bottoneOkAutori = new QPushButton(SezioneArticoli);
        bottoneOkAutori->setObjectName(QString::fromUtf8("bottoneOkAutori"));
        bottoneOkAutori->setGeometry(QRect(530, 390, 51, 51));
        bottoneOkAutori->setFont(font12);
        bottoneOkKeyword = new QPushButton(SezioneArticoli);
        bottoneOkKeyword->setObjectName(QString::fromUtf8("bottoneOkKeyword"));
        bottoneOkKeyword->setGeometry(QRect(530, 460, 51, 51));
        bottoneOkKeyword->setFont(font12);
        bottoneArticolo = new QPushButton(SezioneArticoli);
        bottoneArticolo->setObjectName(QString::fromUtf8("bottoneArticolo"));
        bottoneArticolo->setGeometry(QRect(720, 160, 231, 51));
        bottoneArticolo->setFont(font12);
        label_33 = new QLabel(SezioneArticoli);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(40, 330, 351, 41));
        QFont font25;
        font25.setFamily(QString::fromUtf8("8514oem"));
        font25.setPointSize(15);
        font25.setBold(false);
        font25.setWeight(50);
        label_33->setFont(font25);
        listaArticoli = new QListWidget(SezioneArticoli);
        listaArticoli->setObjectName(QString::fromUtf8("listaArticoli"));
        listaArticoli->setGeometry(QRect(390, 330, 111, 41));
        label_30 = new QLabel(SezioneArticoli);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(300, 260, 371, 51));
        QFont font26;
        font26.setFamily(QString::fromUtf8("HP Simplified Jpan Light"));
        font26.setPointSize(20);
        font26.setBold(false);
        font26.setWeight(50);
        label_30->setFont(font26);
        label_31 = new QLabel(SezioneArticoli);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(50, 170, 61, 31));
        label_31->setFont(font24);
        prezzoArticolo = new QDoubleSpinBox(SezioneArticoli);
        prezzoArticolo->setObjectName(QString::fromUtf8("prezzoArticolo"));
        prezzoArticolo->setGeometry(QRect(130, 170, 91, 31));
        prezzoArticolo->setMaximum(9999.989999999999782);
        label_34 = new QLabel(SezioneArticoli);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(640, 350, 331, 31));
        label_34->setFont(font3);
        aggiuntaArticoloCorrelato = new QLineEdit(SezioneArticoli);
        aggiuntaArticoloCorrelato->setObjectName(QString::fromUtf8("aggiuntaArticoloCorrelato"));
        aggiuntaArticoloCorrelato->setGeometry(QRect(640, 390, 251, 51));
        bottoneArticoloCorrelato = new QPushButton(SezioneArticoli);
        bottoneArticoloCorrelato->setObjectName(QString::fromUtf8("bottoneArticoloCorrelato"));
        bottoneArticoloCorrelato->setGeometry(QRect(910, 390, 51, 51));
        bottoneArticoloCorrelato->setFont(font12);
        label_36 = new QLabel(SezioneArticoli);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(250, 175, 271, 21));
        label_36->setFont(font3);
        rivistaRiferimento = new QLineEdit(SezioneArticoli);
        rivistaRiferimento->setObjectName(QString::fromUtf8("rivistaRiferimento"));
        rivistaRiferimento->setGeometry(QRect(520, 170, 121, 31));
        label_37 = new QLabel(SezioneArticoli);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(250, 210, 221, 31));
        label_37->setFont(font3);
        conferenzaRiferimento = new QLineEdit(SezioneArticoli);
        conferenzaRiferimento->setObjectName(QString::fromUtf8("conferenzaRiferimento"));
        conferenzaRiferimento->setGeometry(QRect(580, 210, 111, 31));
        annullaArticolo = new QPushButton(SezioneArticoli);
        annullaArticolo->setObjectName(QString::fromUtf8("annullaArticolo"));
        annullaArticolo->setGeometry(QRect(740, 220, 211, 31));
        homeGestore_6 = new QPushButton(SezioneArticoli);
        homeGestore_6->setObjectName(QString::fromUtf8("homeGestore_6"));
        homeGestore_6->setGeometry(QRect(790, 20, 181, 28));
        homeGestore_6->setFont(font4);
        label_49 = new QLabel(SezioneArticoli);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(440, 170, 81, 31));
        label_51 = new QLabel(SezioneArticoli);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(480, 210, 71, 31));
        tabWidget->addTab(SezioneArticoli, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        label_39 = new QLabel(tab);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(70, 30, 901, 41));
        QFont font27;
        font27.setFamily(QString::fromUtf8("HP Simplified"));
        font27.setPointSize(12);
        font27.setBold(true);
        font27.setWeight(75);
        label_39->setFont(font27);
        importa_autori = new QPushButton(tab);
        importa_autori->setObjectName(QString::fromUtf8("importa_autori"));
        importa_autori->setGeometry(QRect(90, 150, 191, 51));
        importa_conferenze = new QPushButton(tab);
        importa_conferenze->setObjectName(QString::fromUtf8("importa_conferenze"));
        importa_conferenze->setGeometry(QRect(310, 150, 211, 51));
        importa_riviste = new QPushButton(tab);
        importa_riviste->setObjectName(QString::fromUtf8("importa_riviste"));
        importa_riviste->setGeometry(QRect(560, 150, 191, 51));
        importa_articoli = new QPushButton(tab);
        importa_articoli->setObjectName(QString::fromUtf8("importa_articoli"));
        importa_articoli->setGeometry(QRect(780, 150, 191, 51));
        tabWidget->addTab(tab, QString());
        stackedWidget->addWidget(sezioneInserimento);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1058, 26));
        MainWindow->setMenuBar(menubar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(4);
        tabWidget_2->setCurrentIndex(1);
        tabWidget->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "Progetto Di Vittorio Matranga", nullptr));
        bottoneInserimento->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        LOGOUNICAL_2->setText(QString());
        freccia_2->setText(QString());
        label_45->setText(QCoreApplication::translate("MainWindow", "Da questo pannello puoi accedere ai dati mediante l'utilizzo dei tab e tornare al pannello di inserimento.", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindow", "Benvenuto nel pannello gestione", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(startGestore), QCoreApplication::translate("MainWindow", "START", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "VISUALIZZA TUTTI GLI AUTORI", nullptr));
        aggiornaAutori->setText(QCoreApplication::translate("MainWindow", "AGGIORNA", nullptr));
        homeInserimento_3->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(AutoriGestore), QCoreApplication::translate("MainWindow", "Autori", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "VISUALIZZA TUTTE LE CONFERENZE", nullptr));
        aggiornaConferenze->setText(QCoreApplication::translate("MainWindow", "AGGIORNA", nullptr));
        homeInserimento_4->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(ConferenzeGestione), QCoreApplication::translate("MainWindow", "Conferenze", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "VISUALIZZA TUTTE LE RIVISTE", nullptr));
        aggiornaRiviste->setText(QCoreApplication::translate("MainWindow", "AGGIORNA", nullptr));
        homeInserimento_5->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(RivisteGestione), QCoreApplication::translate("MainWindow", "Riviste", nullptr));
        aggiornaArticoli->setText(QCoreApplication::translate("MainWindow", "AGGIORNA", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "VISUALIZZA TUTTI GLI ARTICOLI", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "ALTRE OPERAZIONI", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(ArticoliGestione), QCoreApplication::translate("MainWindow", "Articoli", nullptr));
        bottoneConferenza->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "CERCA ARTICOLI PER CONFERENZA (ACRONIMO E LUOGO)", nullptr));
        homeGestore->setText(QCoreApplication::translate("MainWindow", "SEZIONE GESTIONE", nullptr));
        ricercaRivista->setText(QString());
        bottoneRivista_Ricerca->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "CERCA ARTICOLI PER RIVISTA (ACRONIMO)", nullptr));
        label_48->setText(QCoreApplication::translate("MainWindow", "CERCA ARTICOLI PER KEYWORD", nullptr));
        bottoneKeyword_Ricerca->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        ricercaKeyword->setText(QString());
        homeInserimento->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        goToPage2->setText(QCoreApplication::translate("MainWindow", "ALTRE OPERAZIONI (2)", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "ACRONIMO", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "LUOGO", nullptr));
        label_53->setText(QCoreApplication::translate("MainWindow", "ACRONIMO", nullptr));
        label_54->setText(QCoreApplication::translate("MainWindow", "VOL", nullptr));
        ricercaRivistaVolume->setText(QString());
        homeGestore_7->setText(QCoreApplication::translate("MainWindow", "SEZIONE GESTIONE", nullptr));
        backToPag2->setText(QCoreApplication::translate("MainWindow", "INDIETRO (2)", nullptr));
        homeInserimento_6->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        articoliKeywordAnnoDecrescente->setText(QString());
        label_140->setText(QCoreApplication::translate("MainWindow", "ID:", nullptr));
        bottone_ArticoliKeywordAnnoDecrescente->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label_141->setText(QCoreApplication::translate("MainWindow", "Articoli Keyword METODO 5 SEZ D", nullptr));
        mediaAutore->setText(QString());
        bottone_mediaAutori->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "Media prezzi per autore", nullptr));
        homeInserimento_2->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        homeGestore_2->setText(QCoreApplication::translate("MainWindow", "SEZIONE GESTIONE", nullptr));
        backToPag1->setText(QCoreApplication::translate("MainWindow", "INDIETRO (1)", nullptr));
        label_136->setText(QCoreApplication::translate("MainWindow", "Keyword pi\303\271 redditizie", nullptr));
        bottone_keywordRedditizie->setText(QCoreApplication::translate("MainWindow", "AGGIORNA", nullptr));
        label_137->setText(QCoreApplication::translate("MainWindow", "Vista Rapida autori", nullptr));
        label_138->setText(QCoreApplication::translate("MainWindow", "Articoli Autore ordinati per prezzo", nullptr));
        articoliAutorePrezzo->setText(QString());
        bottone_ArticoliAutorePrezzo->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label_139->setText(QCoreApplication::translate("MainWindow", "ID:", nullptr));
        label_144->setText(QCoreApplication::translate("MainWindow", "Articoli dal prezzo pi\303\271 alto (Autore)", nullptr));
        label_145->setText(QCoreApplication::translate("MainWindow", "ID:", nullptr));
        bottone_ArticoliAutorePrezzoAlto->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        articoliAutorePrezzoAlto->setText(QString());
        goToPage3->setText(QCoreApplication::translate("MainWindow", "ALTRE OPERAZIONI (3)", nullptr));
        bottoneGestione->setText(QCoreApplication::translate("MainWindow", "GESTORE", nullptr));
        LOGOUNICAL->setText(QString());
        label_43->setText(QCoreApplication::translate("MainWindow", "Benvenuto nella pagina principale", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "Da questo pannello puoi inserire i dati mediante l'utilizzo dei tab e poi passare al pannello gestionale.", nullptr));
        freccia->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(START), QCoreApplication::translate("MainWindow", "START", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Nome:", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Cognome:", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "ID:", nullptr));
        bottoneAutore->setText(QCoreApplication::translate("MainWindow", "Aggiungi Autore", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Aggiungi afferenze di:", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "INSERISCI:", nullptr));
        bottoneAfferenza->setText(QCoreApplication::translate("MainWindow", "Aggiungi afferenza", nullptr));
        annullaAutore->setText(QCoreApplication::translate("MainWindow", "ANNULLA INSERIMENTO", nullptr));
        homeGestore_3->setText(QCoreApplication::translate("MainWindow", "SEZIONE GESTIONE", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(SezioneAutori), QCoreApplication::translate("MainWindow", "Autore", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Acronimo:", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Luogo:", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Nome:", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Numero partecipanti:", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "Selezionare data:", nullptr));
        bottoneConferenze->setText(QCoreApplication::translate("MainWindow", "Aggiungi Conferenza", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Aggiungi organizzatori di:", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "INSERISCI:", nullptr));
        bottoneOrganizzatori->setText(QCoreApplication::translate("MainWindow", "Aggiungi organizzatore", nullptr));
        annullaConferenza->setText(QCoreApplication::translate("MainWindow", "ANNULLA INSERIMENTO", nullptr));
        homeGestore_4->setText(QCoreApplication::translate("MainWindow", "SEZIONE GESTIONE", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(SezioneConferenza), QCoreApplication::translate("MainWindow", "Conferenza", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Nome:", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Selezionare data:", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Acronimo:", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "Volume:", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "Editore:", nullptr));
        bottoneRivista->setText(QCoreApplication::translate("MainWindow", "Aggiungi Rivista", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Hai aggiunto le seguenti riviste:", nullptr));
        annullaRivista->setText(QCoreApplication::translate("MainWindow", "ANNULLA INSERIMENTO", nullptr));
        homeGestore_5->setText(QCoreApplication::translate("MainWindow", "SEZIONE GESTIONE", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(SezioneRivista), QCoreApplication::translate("MainWindow", "Rivista", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "ID:", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "Titolo:", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "Numero di pagine:", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "INSERIMENTO DATI", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "AGGIUNGI ID AUTORE:", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "AGGIUNGI KEYWORD:", nullptr));
#if QT_CONFIG(tooltip)
        aggiuntaAutoreArticolo->setToolTip(QCoreApplication::translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        aggiuntaAutoreArticolo->setWhatsThis(QCoreApplication::translate("MainWindow", "<html><head/><body><p>Prova</p></body></html>", nullptr));
#endif // QT_CONFIG(whatsthis)
        aggiuntaAutoreArticolo->setText(QString());
        bottoneOkAutori->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        bottoneOkKeyword->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        bottoneArticolo->setText(QCoreApplication::translate("MainWindow", "AGGIUNGI ARTICOLO", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "STAI OPERANDO SULL'ARTICOLO (ID):", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "INFORMAZIONI AGGIUNTIVE", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "Prezzo:", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "AGGIUNGI ID ARTICOLO CORRELATO:", nullptr));
#if QT_CONFIG(tooltip)
        aggiuntaArticoloCorrelato->setToolTip(QCoreApplication::translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", nullptr));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        aggiuntaArticoloCorrelato->setWhatsThis(QCoreApplication::translate("MainWindow", "<html><head/><body><p>Prova</p></body></html>", nullptr));
#endif // QT_CONFIG(whatsthis)
        aggiuntaArticoloCorrelato->setText(QString());
        bottoneArticoloCorrelato->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Rivista di riferimento", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Conferenza di riferimento", nullptr));
        annullaArticolo->setText(QCoreApplication::translate("MainWindow", "ANNULLA INSERIMENTO", nullptr));
        homeGestore_6->setText(QCoreApplication::translate("MainWindow", "SEZIONE GESTIONE", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindow", "Acronimo", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindow", "Acronimo", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(SezioneArticoli), QCoreApplication::translate("MainWindow", "Articolo", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Tramite questa sezione \303\250 possibile importare, mediante file di testo .txt, ogni tipologia di dato.", nullptr));
        importa_autori->setText(QCoreApplication::translate("MainWindow", "IMPORTA AUTORI", nullptr));
        importa_conferenze->setText(QCoreApplication::translate("MainWindow", "IMPORTA CONFERENZE", nullptr));
        importa_riviste->setText(QCoreApplication::translate("MainWindow", "IMPORTA RIVISTE", nullptr));
        importa_articoli->setText(QCoreApplication::translate("MainWindow", "IMPORTA ARTICOLI", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("MainWindow", "IMPORTA", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
